name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npx playwright test fakestore_coverage_api.spec.js
    - name: Upload Coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: reports/index.html
        retention-days: 30
        if-no-files-found: ignore
    - name: Semantic Release 🚀
      uses: cycjimmy/semantic-release-action@v4
      with:
        branch: main
        tag_format: v${version}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
